# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumb_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumb_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
