# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170217_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbs'),
        ),
    ]
