# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170217_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='gallery/thumbs'),
        ),
    ]
